"""
Translate French topics to Portuguese.
"""

# Portuguese translations of the French topics
portuguese_topics = [
    "As leis de herança na Grécia antiga",
    "As regras de vestimenta em Esparta",
    "As restrições de movimento das mulheres em Atenas",
    "As mulheres na Roma antiga",
    "Os direitos das mulheres no Egito antigo",
    "Cleópatra e o poder feminino",
    "As mulheres guerreiras na história",
    "As Amazonas: mito e realidade",
    "As mulheres no Império Bizantino",
    "As rainhas medievais da Europa",
    "As mulheres na Pérsia antiga",
    "As gueixas no Japão",
    "As mulheres vikings",
    "As tradições indianas antigas e as mulheres",
    "As mulheres na China antiga",
    "As sacerdotisas nas culturas antigas",
    "As mulheres filósofas da Antiguidade",
    "A beleza e os cosméticos na Antiguidade",
    "Os costumes matrimoniais das civilizações antigas",
    "A educação das mulheres na história",
    "As mulheres e a religião na Antiguidade",
    "A maternidade nas culturas antigas",
    "As mulheres líderes na história",
    "As deusas antigas e seus cultos",
    "A moda feminina através das épocas",
    "As mulheres na arte antiga",
    "O papel das mulheres na medicina antiga",
    "As mulheres e a magia na história",
    "As profissões femininas antigas",
    "As mulheres na literatura antiga",
    "Nefertiti e o poder feminino no Egito",
    "As mulheres na Mesopotâmia antiga",
    "As mulheres espartanas e suas liberdades",
    "As hetairas atenienses e seu papel",
    "As mulheres na Índia antiga",
    "As mulheres samurais no Japão",
    "As Valquírias na mitologia escandinava",
    "As mulheres no Israel antigo",
    "As imperatrizes romanas e sua influência",
    "As mulheres no cristianismo primitivo",
    "As mulheres sacerdotisas na Grécia antiga",
    "As rainhas do Egito antigo",
    "As mulheres na cultura celta",
    "As mulheres maias e astecas",
    "As mulheres na Babilônia antiga",
    "As mulheres faraós do Egito",
    "As imperatrizes chinesas antigas",
    "As mulheres na idade de ouro islâmica",
    "As mulheres na Fenícia antiga",
    "As mulheres xamãs nas culturas antigas",
    "As mulheres na Coreia antiga",
    "As mulheres da Núbia antiga",
    "As mulheres no Império Persa",
    "As mulheres poetisas da Antiguidade",
    "As vestais romanas",
    "As mulheres na Armênia antiga",
    "As mulheres matemáticas da Antiguidade",
    "As mulheres na Etiópia antiga",
    "As mulheres médicas na Antiguidade",
    "As mulheres em Cartago antiga",
    "As mulheres astrônomas da Antiguidade",
    "As mulheres na Síria antiga",
    "As mulheres artistas da Antiguidade",
    "As mulheres no Irã antigo",
    "As mulheres musicistas da Antiguidade",
    "As mulheres na Anatólia antiga",
    "As mulheres escultoras da Antiguidade",
    "As mulheres na Palestina antiga",
    "As mulheres alquimistas da Antiguidade",
    "As mulheres na Arábia antiga",
    "As mulheres dançarinas da Antiguidade",
    "As mulheres no Sudão antigo",
    "As mulheres tecelãs na Antiguidade",
    "As mulheres na Líbia antiga",
    "As mulheres perfumistas da Antiguidade",
    "As mulheres em Creta antiga",
    "As mulheres joalheiras da Antiguidade",
    "As mulheres na Trácia antiga",
    "As mulheres oleiras da Antiguidade",
    "As mulheres na Cítia antiga",
    "As mulheres padeiras da Antiguidade",
    "As mulheres na Judeia antiga",
    "As mulheres vinicultoras da Antiguidade",
    "As mulheres na Macedônia antiga",
    "As mulheres parteiras da Antiguidade",
    "As mulheres na Gália antiga",
    "As mulheres amas na Antiguidade",
    "As mulheres na Ibéria antiga",
    "As mulheres cozinheiras da Antiguidade",
    "As mulheres na Dácia antiga",
    "As mulheres jardineiras da Antiguidade",
    "As mulheres na Báctria antiga",
    "As mulheres pastoras da Antiguidade",
    "As mulheres na Sogdiana antiga",
    "As mulheres pescadoras da Antiguidade",
    "As mulheres na Pártia antiga",
    "As mulheres caçadoras da Antiguidade",
    "As mulheres no Corásmia antiga",
    "As mulheres comerciantes na Antiguidade",
    "As mulheres na Cólquida antiga",
    "As mulheres lavadeiras da Antiguidade",
    "As mulheres na Lídia antiga",
    "As mulheres tintureiras da Antiguidade",
    "As mulheres na Capadócia antiga",
    "As mulheres sapateiras da Antiguidade",
    "As mulheres no Ponto antigo",
    "As mulheres costureiras da Antiguidade",
    "As mulheres na Cilícia antiga",
    "As mulheres bordadeiras da Antiguidade",
    "As mulheres em Urartu antiga",
    "As mulheres fiandeiras da Antiguidade",
    "As mulheres na Frígia antiga",
    "As mulheres rendeiras da Antiguidade",
    "As mulheres em Elam antiga",
    "As mulheres alfaiates na Antiguidade",
    "As mulheres na Média antiga",
    "As mulheres modistas da Antiguidade",
    "As mulheres na Assíria antiga",
    "As mulheres chapeleiras da Antiguidade",
    "As mulheres na Suméria antiga",
    "As mulheres luvas da Antiguidade",
    "As mulheres em Acádia antiga",
    "As mulheres espartilheiras da Antiguidade",
    "As mulheres em Troia antiga",
    "As mulheres fabricantes de bonés da Antiguidade",
    "As mulheres em Micenas antigas",
    "As mulheres calçadistas da Antiguidade",
    "As mulheres em Tiro antiga",
    "As mulheres marroquineiras da Antiguidade",
    "As mulheres em Sidom antiga",
    "As mulheres guarda-chuvas da Antiguidade",
    "As mulheres em Biblos antiga",
    "As mulheres leques da Antiguidade",
    "As mulheres em Ugarit antiga",
    "As mulheres pentes da Antiguidade",
    "As mulheres em Palmira antiga",
    "As mulheres espelhos da Antiguidade",
    "As mulheres em Petra antiga",
    "As mulheres ceramistas da Antiguidade",
    "As mulheres no reino nabateu antigo",
    "As mulheres sopradoras de vidro da Antiguidade",
    "As mulheres em Pérgamo antiga",
    "As mulheres mosaicistas da Antiguidade",
    "As mulheres em Éfeso antiga",
    "As mulheres afresquistas da Antiguidade",
    "As mulheres em Mileto antiga",
    "As mulheres iconógrafas da Antiguidade",
    "As mulheres em Halicarnasso antiga",
    "As mulheres miniaturistas da Antiguidade",
    "As mulheres em Esmirna antiga",
    "As mulheres calígrafas da Antiguidade",
    "As mulheres em Priene antiga",
    "As mulheres copistas da Antiguidade",
    "As mulheres em Magnésia antiga",
    "As mulheres bibliotecárias da Antiguidade",
    "As mulheres em Sardes antigas",
    "As mulheres arquivistas da Antiguidade",
    "As mulheres em Dídima antiga",
    "As mulheres cronistas da Antiguidade",
    "As mulheres em Afrodísias antiga",
    "As mulheres analistas da Antiguidade",
    "As mulheres em Cnido antiga",
    "As mulheres historiadoras da Antiguidade",
    "As mulheres na Galácia antiga",
    "As mulheres geógrafas da Antiguidade",
    "As mulheres na Panfília antiga",
    "As mulheres cartógrafas da Antiguidade",
    "As mulheres na Lícia antiga",
    "As mulheres navegadoras da Antiguidade",
    "As mulheres na Cária antiga",
    "As mulheres marinheiras da Antiguidade",
    "As mulheres na Pisídia antiga",
    "As mulheres capitãs de navios",
    "As mulheres na Isaúria antiga",
    "As mulheres pilotos da Antiguidade",
    "As mulheres em Rodes antiga",
    "As mulheres timoneiras da Antiguidade",
    "As mulheres em Chipre antiga",
    "As mulheres marinheiras da Antiguidade",
    "As mulheres em Samos antiga",
    "As mulheres construtoras de navios da Antiguidade",
    "As mulheres em Quios antiga",
    "As mulheres veleiras da Antiguidade",
    "As mulheres em Lesbos antiga",
    "As mulheres cordoeiras da Antiguidade",
    "As mulheres em Delos antiga",
    "As mulheres âncoras da Antiguidade",
    "As mulheres em Naxos antiga",
    "As mulheres aparelheiras da Antiguidade",
    "As mulheres em Paros antiga",
    "As mulheres estivadoras da Antiguidade",
    "As mulheres em Melos antiga",
    "As mulheres descarregadoras da Antiguidade",
    "As mulheres em Tenos antiga",
    "As mulheres portuárias da Antiguidade",
    "As mulheres em Andros antiga",
    "As mulheres alfandegárias da Antiguidade",
    "As mulheres em Ceos antiga",
    "As mulheres coletoras de impostos",
    "As mulheres em Sifnos antiga",
    "As mulheres contadoras da Antiguidade",
    "As mulheres em Serifos antiga",
    "As mulheres tesoureiras da Antiguidade",
    "As mulheres em Citnos antiga",
    "As mulheres cambistas da Antiguidade",
    "As mulheres em Miconos antiga",
    "As mulheres credoras da Antiguidade",
    "As mulheres em Ios antiga",
    "As mulheres banqueiras da Antiguidade",
    "As mulheres em Amorgos antiga",
    "As mulheres financeiras da Antiguidade",
    "As mulheres em Santorini antiga",
    "As mulheres investidoras da Antiguidade",
    "As mulheres em Creta minoica",
    "As mulheres mecenas da Antiguidade",
    "As mulheres em Gortina antiga",
    "As mulheres benfeitoras da Antiguidade",
    "As mulheres em Cnossos antiga",
    "As mulheres filantropas da Antiguidade",
    "As mulheres em Festos antiga",
    "As mulheres patrocinadoras da Antiguidade",
    "As mulheres em Mália antiga",
    "As mulheres patronas da Antiguidade",
    "As mulheres em Zacros antiga",
    "As mulheres protetoras das artes",
    "As mulheres em Kato Zakro antiga",
    "As mulheres mecenas das ciências",
    "As mulheres em Palaikastro antiga",
    "As mulheres fundadoras de escolas",
    "As mulheres em Gournia antiga",
    "As mulheres criadoras de bibliotecas",
    "As mulheres em Vasiliki antiga",
    "As mulheres fundadoras de museus",
    "As mulheres em Pseira antiga",
    "As mulheres organizadoras de teatros",
    "As mulheres em Mochlos antiga",
    "As mulheres construtoras de termas",
    "As mulheres em Petras antiga",
    "As mulheres construtoras de aquedutos",
    "As mulheres em Kato Symi antiga",
    "As mulheres arquitetas da Antiguidade",
    "As mulheres em Archanes antiga",
    "As mulheres urbanistas da Antiguidade",
    "As mulheres em Amnissos antiga",
    "As mulheres engenheiras da Antiguidade",
    "As mulheres em Tylissos antiga",
    "As mulheres mecânicas da Antiguidade",
    "As mulheres em Vathypetro antiga",
    "As mulheres inventoras da Antiguidade",
    "As mulheres em Agia Triada antiga",
    "As mulheres inovadoras da Antiguidade",
    "As mulheres em Kommos antiga",
    "As mulheres experimentadoras da Antiguidade",
    "As mulheres em Matala antiga",
    "As mulheres pesquisadoras da Antiguidade",
    "As mulheres em Lebena antiga",
    "As mulheres descobridoras da Antiguidade",
    "As mulheres em Lato antiga",
    "As mulheres viajantes da Antiguidade",
    "As mulheres em Dreros antiga",
    "As mulheres peregrinas da Antiguidade",
    "As mulheres em Praisos antiga",
    "As mulheres vagabundas da Antiguidade",
    "As mulheres em Itanos antiga",
    "As mulheres nômades da Antiguidade",
    "As mulheres em Olonte antiga",
    "As mulheres migrantes da Antiguidade",
    "As mulheres em Eleutherna antiga",
    "As mulheres refugiadas da Antiguidade",
    "As mulheres em Axos antiga",
    "As mulheres emigradas da Antiguidade",
    "As mulheres em Eleftherna antiga",
    "As mulheres imigradas da Antiguidade",
    "As mulheres em Rizenia antiga",
    "As mulheres colonizadoras da Antiguidade",
    "As mulheres em Aptera antiga",
    "As mulheres pioneiras da Antiguidade",
    "As mulheres em Polirênia antiga",
    "As mulheres colonas da Antiguidade",
    "As mulheres em Falasarna antiga",
    "As mulheres fundadoras de colônias",
    "As mulheres em Kissamos antiga",
    "As mulheres pioneiras de novas terras",
    "As mulheres em Kantanos antiga",
    "As mulheres desbravadoras de territórios",
    "As mulheres em Lissos antiga",
    "As mulheres exploradoras da Antiguidade",
    "As mulheres em Sybritos antiga",
    "As mulheres aventureiras da Antiguidade",
    "As mulheres em Elyros antiga",
    "As mulheres navegadoras de mares",
    "As mulheres em Tarra antiga",
    "As mulheres exploradoras marítimas",
    "As mulheres em Inachorion antiga",
    "As mulheres descobridoras de rotas",
    "As mulheres em Gortys antiga",
    "As mulheres cartógrafas marítimas",
    "As mulheres em Lebena de Creta",
    "As mulheres navegadoras dos mares antigos",
    "As mulheres em Festos de Creta",
    "As mulheres pilotos da Antiguidade",
    "As mulheres em Agia Triada de Creta",
    "As mulheres pilotos de rotas marítimas",
    "As mulheres em Matala de Creta",
    "As mulheres capitãs de navios mercantes",
    "As mulheres em Kommos de Creta",
    "As mulheres proprietárias de frotas",
    "As mulheres em Kaloi Limenes antiga",
    "As mulheres armadoras da Antiguidade",
    "As mulheres em Lendas antiga",
    "As mulheres negociantes marítimas",
    "As mulheres em Keratokampos antiga",
    "As mulheres exportadoras de mercadorias",
    "As mulheres em Ierapetra antiga",
    "As mulheres importadoras da Antiguidade",
    "As mulheres em Makrygialos antiga",
    "As mulheres atacadistas da Antiguidade",
    "As mulheres em Koufonisi antiga",
    "As mulheres varejistas da Antiguidade",
    "As mulheres em Chrysi antiga",
    "As mulheres comerciantes de mercado",
    "As mulheres em Gavdos antiga",
    "As mulheres comerciantes de bazar",
    "As mulheres em Paleochora antiga",
    "As mulheres comerciantes de feira",
    "As mulheres em Sougia antiga",
    "As mulheres caravaneiras da Antiguidade",
    "As mulheres em Frangokastello antiga",
    "As mulheres condutoras de caravanas",
    "As mulheres em Sfakia antiga",
    "As mulheres guias de caravanas",
    "As mulheres em Chora Sfakion antiga",
    "As mulheres organizadoras de rotas comerciais",
    "As mulheres em Loutro antiga",
    "As mulheres agentes aduaneiras",
    "As mulheres em Agia Roumeli antiga",
    "As mulheres coletoras de taxas",
    "As mulheres em Samaria antiga",
    "As mulheres inspetoras do comércio",
    "As mulheres em Omalos antiga",
    "As mulheres controladoras de qualidade",
    "As mulheres em Chania antiga",
    "As mulheres avaliadoras de mercadorias",
    "As mulheres em Cidônia antiga",
    "As mulheres pesadoras da Antiguidade",
    "As mulheres em Retimno antiga",
    "As mulheres medidoras da Antiguidade",
    "As mulheres em Heraclião antiga",
    "As mulheres contadoras comerciais",
    "As mulheres escribas do Egito antigo",
    "As mulheres guerreiras celtas",
    "As mulheres druidas na Antiguidade",
    "As mulheres oráculos de Delfos",
    "As mulheres gladiadoras romanas",
    "As mulheres piratas da Antiguidade",
    "As mulheres estrategistas militares",
    "As mulheres diplomatas antigas",
    "As mulheres embaixadoras da Antiguidade",
    "As mulheres espiãs na história antiga",
    "As mulheres conselheiras reais",
    "As mulheres regentes na Antiguidade",
    "As mulheres legisladoras antigas",
    "As mulheres juízas da Antiguidade",
    "As mulheres advogadas no mundo antigo",
    "As mulheres notárias da Antiguidade",
    "As mulheres escribas reais",
    "As mulheres secretárias imperiais",
    "As mulheres tradutoras da Antiguidade",
    "As mulheres intérpretes antigas",
    "As mulheres professoras da Antiguidade",
    "As mulheres docentes no mundo antigo",
    "As mulheres tutoras de príncipes",
    "As mulheres governantas reais",
    "As mulheres preceptoras da Antiguidade",
    "As mulheres educadoras de meninas",
    "As mulheres diretoras de escolas",
    "As mulheres fundadoras de academias",
    "As mulheres retóricas da Antiguidade",
    "As mulheres oradoras antigas",
    "As mulheres debatedoras da Antiguidade",
    "As mulheres sofistas gregas",
    "As mulheres estoicas da Antiguidade",
    "As mulheres epicuristas antigas",
    "As mulheres pitagóricas",
    "As mulheres platônicas da Antiguidade",
    "As mulheres aristotélicas",
    "As mulheres cínicas da Antiguidade",
    "As mulheres céticas antigas",
    "As mulheres neoplatônicas",
    "As mulheres gnósticas da Antiguidade",
    "As mulheres místicas antigas",
    "As mulheres visionárias da Antiguidade",
    "As mulheres profetisas antigas",
    "As mulheres sibilas da Antiguidade",
    "As mulheres adivinhas antigas",
    "As mulheres astrólogas da Antiguidade",
    "As mulheres áugures romanas",
    "As mulheres harúspices da Antiguidade",
    "As mulheres magas antigas",
    "As mulheres feiticeiras da Antiguidade",
    "As mulheres curandeiras antigas",
    "As mulheres herbalistas da Antiguidade",
    "As mulheres boticárias antigas",
    "As mulheres farmacêuticas da Antiguidade",
    "As mulheres cirurgiãs antigas",
    "As mulheres dentistas da Antiguidade",
    "As mulheres oftalmologistas antigas",
    "As mulheres veterinárias da Antiguidade",
    "As mulheres botânicas antigas",
    "As mulheres zoólogas da Antiguidade",
    "As mulheres naturalistas antigas",
    "As mulheres químicas da Antiguidade",
    "As mulheres físicas antigas",
    "As mulheres matemáticas gregas",
    "As mulheres geômetras da Antiguidade",
    "As mulheres algebristas antigas",
    "As mulheres aritméticas da Antiguidade",
    "As mulheres lógicas antigas",
    "As mulheres astrônomas babilônicas",
    "As mulheres cosmólogas da Antiguidade",
    "As mulheres meteorologistas antigas",
    "As mulheres geólogas da Antiguidade",
    "As mulheres mineralogistas antigas",
    "As mulheres metalurgistas da Antiguidade",
    "As mulheres ferreiras antigas",
    "As mulheres ourives da Antiguidade",
    "As mulheres prateiras antigas",
    "As mulheres bronzistas da Antiguidade",
    "As mulheres ferreiras antigas",
    "As mulheres armeiras da Antiguidade",
    "As mulheres fabricantes de armas",
    "As mulheres escudeiras da Antiguidade",
    "As mulheres fabricantes de capacetes",
    "As mulheres couraças da Antiguidade",
    "As mulheres fabricantes de espadas",
    "As mulheres lanceiras da Antiguidade",
    "As mulheres arqueiras antigas",
    "As mulheres fundeiras da Antiguidade",
    "As mulheres cavaleiras antigas",
    "As mulheres aurigas da Antiguidade",
    "As mulheres domadoras de cavalos",
    "As mulheres criadoras da Antiguidade",
    "As mulheres pastoras antigas",
    "As mulheres leiteiras da Antiguidade",
    "As mulheres queijeiras antigas",
    "As mulheres apicultoras da Antiguidade",
    "As mulheres sericultoras antigas",
    "As mulheres cultivadoras da Antiguidade",
    "As mulheres agricultoras antigas",
    "As mulheres vinicultoras gaulesas",
    "As mulheres oleicultoras da Antiguidade",
    "As mulheres cerealistas antigas",
    "As mulheres horticultoras da Antiguidade",
    "As mulheres fruteiras antigas",
    "As mulheres floricultoras da Antiguidade",
    "As mulheres horticultoras antigas",
    "As mulheres paisagistas da Antiguidade",
    "As mulheres florestais antigas",
    "As mulheres lenheiras da Antiguidade",
    "As mulheres carpinteiras antigas",
    "As mulheres marceneiras da Antiguidade",
    "As mulheres ebanistas antigas",
    "As mulheres escultoras em madeira",
    "As mulheres torneiras da Antiguidade",
    "As mulheres cesteiras antigas",
    "As mulheres esparteiras da Antiguidade",
    "As mulheres de vime da Antiguidade",
    "As mulheres de papiro do Egito antigo",
    "As mulheres de pergaminho da Antiguidade",
    "As mulheres iluminadoras antigas",
    "As mulheres encadernadoras da Antiguidade",
    "As mulheres livreiras antigas",
    "As mulheres editoras da Antiguidade",
    "As mulheres impressoras antigas",
    "As mulheres gravadoras da Antiguidade",
    "As mulheres litógrafas antigas",
    "As mulheres pintoras egípcias",
    "As mulheres pintoras gregas",
    "As mulheres pintoras romanas",
    "As mulheres retratistas da Antiguidade",
    "As mulheres paisagistas antigas",
    "As mulheres afresquistas pompeianas",
    "As mulheres muralistas da Antiguidade",
    "As mulheres ceramistas gregas",
    "As mulheres oleiras etruscas",
    "As mulheres vidreiras fenícias",
    "As mulheres esmaltadoras da Antiguidade",
    "As mulheres joalheiras antigas",
    "As mulheres gemólogas da Antiguidade",
    "As mulheres lapidárias antigas",
    "As mulheres cortadoras de pedras preciosas",
    "As mulheres perleiras da Antiguidade",
    "As mulheres coraleiras antigas",
    "As mulheres âmbar da Antiguidade",
    "As mulheres marfins antigas",
    "As mulheres ebanistas egípcias",
    "As mulheres marcheteiras da Antiguidade",
    "As mulheres intarsiadoras antigas",
    "As mulheres douradoras da Antiguidade",
    "As mulheres prateadoras antigas",
    "As mulheres lacadoras da Antiguidade",
    "As mulheres envernizadoras antigas",
    "As mulheres polidoras da Antiguidade",
    "As mulheres cereiras antigas",
    "As mulheres candeleiras da Antiguidade",
    "As mulheres saboeiras antigas",
    "As mulheres perfumistas egípcias",
    "As mulheres cosmetologistas da Antiguidade",
    "As mulheres cabeleireiras antigas",
    "As mulheres barbeiras da Antiguidade",
    "As mulheres manicures antigas",
    "As mulheres pedicures da Antiguidade",
    "As mulheres massagistas antigas",
    "As mulheres banhistas da Antiguidade",
    "As mulheres termalistas antigas",
    "As mulheres hidroterapeutas da Antiguidade",
    "As mulheres ginastas antigas",
    "As mulheres atletas gregas",
    "As mulheres corredoras da Antiguidade",
    "As mulheres lançadoras antigas",
    "As mulheres discóbolas da Antiguidade",
    "As mulheres saltadoras antigas",
    "As mulheres lutadoras da Antiguidade",
    "As mulheres boxeadoras antigas",
    "As mulheres pancratiastas da Antiguidade",
    "As mulheres acrobatas antigas",
    "As mulheres equilibristas da Antiguidade",
    "As mulheres malabaristas antigas",
    "As mulheres contorcionistas da Antiguidade",
    "As mulheres mímicas antigas",
    "As mulheres pantomimas da Antiguidade",
    "As mulheres comediantes antigas",
    "As mulheres tragedianas da Antiguidade",
    "As mulheres atrizes gregas",
    "As mulheres atrizes romanas",
    "As mulheres dramaturgas da Antiguidade",
    "As mulheres roteiristas antigas",
    "As mulheres coreógrafas da Antiguidade",
    "As mulheres dançarinas egípcias",
    "As mulheres dançarinas gregas",
    "As mulheres dançarinas indianas",
    "As mulheres dançarinas persas",
    "As mulheres musicistas egípcias",
    "As mulheres harpistas da Antiguidade",
    "As mulheres liristas antigas",
    "As mulheres citaristas da Antiguidade",
    "As mulheres flautistas antigas",
    "As mulheres auletas da Antiguidade",
    "As mulheres trompetistas antigas",
    "As mulheres percussionistas da Antiguidade",
    "As mulheres cimbalistas antigas",
    "As mulheres cantoras da Antiguidade",
    "As mulheres coristas antigas",
    "As mulheres cantatrizes da Antiguidade",
    "As mulheres compositoras antigas",
    "As mulheres poetisas gregas",
    "As mulheres poetisas romanas",
    "As mulheres poetisas árabes",
    "As mulheres poetisas persas",
    "As mulheres romancistas da Antiguidade",
    "As mulheres contadoras antigas",
    "As mulheres fabulistas da Antiguidade",
    "As mulheres epistológrafas antigas",
    "As mulheres memorialistas da Antiguidade",
    "As mulheres biógrafas antigas",
    "As mulheres hagiógrafas da Antiguidade",
    "As mulheres genealogistas antigas",
    "As mulheres heraldistas da Antiguidade",
    "As mulheres arqueólogas antigas",
    "As mulheres epigrafistas da Antiguidade",
    "As mulheres paleógrafas antigas",
    "As mulheres numismatas da Antiguidade",
    "As mulheres sigilógrafas antigas",
    "As mulheres arautos da Antiguidade",
    "As mulheres pregoeiras públicas",
    "As mulheres mensageiras antigas",
    "As mulheres correias da Antiguidade",
    "As mulheres estafetas antigas",
    "As mulheres portadoras de notícias",
    "As mulheres anunciadoras da Antiguidade",
    "As mulheres proclamadoras antigas",
    "As mulheres guardiãs de templos",
    "As mulheres sacristãs da Antiguidade",
    "As mulheres bedéis antigas",
    "As mulheres sineiras de sinos",
    "As mulheres acendedoras de lâmpadas",
    "As mulheres incensadoras da Antiguidade",
    "As mulheres ofertantes antigas",
    "As mulheres libações da Antiguidade",
    "As mulheres sacrificadoras antigas",
    "As mulheres imoladoras da Antiguidade",
    "As mulheres áugures antigas",
    "As mulheres adivinhas por pássaros",
    "As mulheres intérpretes de sonhos",
    "As mulheres oniromantas da Antiguidade",
    "As mulheres quiromantas antigas",
    "As mulheres cartomantes da Antiguidade",
    "As mulheres tarôs antigas",
    "As mulheres rúnicas da Antiguidade",
    "As mulheres geomantas antigas",
]

# Write to topics.txt
with open('topics.txt', 'w', encoding='utf-8') as f:
    for topic in portuguese_topics:
        f.write(f"{topic}\n")

print(f"✅ Created {len(portuguese_topics)} Portuguese topics!")
print(f"📝 Saved to topics.txt")
